services:
  - type: web
    name: discord-welcome-bot
    env: python
    runtime: python-3.12.8
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.8"
