services:
  - type: web
    name: discord-welcome-bot
    env: python
    runtime: python-3.12.8
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
